### ISSUE TITLE
 Cannot use ImageField because Pillow is not installed.

### ISSUE THREAD

**Issue by abhaykatheria** [Shrawan907/djecommerce#3]
Add pillow in req.txt

**Comment by abhaykatheria** [comment]
![image](https://user-images.githubusercontent.com/40055274/85840252-d0e93a80-b7b9-11ea-9aae-8daf3d8ab2c4.png)

**Comment by Shrawan907** [comment]
Package "Pillow" added successfully in requirements.txt, Install all packages in requirements.txt to run code on your system.
